name: wikimedia_commons_search
description: A Dart library for searching and retrieving articles and images from Wikipedia / Wikimedia Commons
version: 1.0.0
homepage: https://github.com/yomio/wikimedia_commons_search
repository: https://github.com/yomio/wikimedia_commons_search.git
issue_tracker: https://github.com/yomio/wikimedia_commons_search/issues
topics:
  - http
  - api
  - network
  - search
  - wikipedia
screenshots:
  - description: 'Example Flutter app using the library - search'
    path: doc/sample0.png
  - description: 'Example Flutter app using the library - topic details'
    path: doc/sample1.png
  - description: 'Example Flutter app using the library - image details'
    path: doc/sample2.png

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.3.0
  equatable: ^2.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

# Test configuration
dart_test:
  tags:
    integration:
      timeout: 2x
      platform: vm
      presets:
        - integration

# Test configuration
targets:
  $default:
    sources:
      include:
        - test/**
        - lib/**
        - $package$
    tests:
      $default:
        exclude:
          - test/**_integration_test.dart
      integration_test:
        include:
          - test/**_integration_test.dart 